module.exports = {
  darkMode: 'class',
  content: ["./public/*.html"],
  safelist: [
    '!stroke-[#eb8307]',
    '!opacity-100',
    '!right-0',
    '!visible',
    '!right-[58px]',
    '!mb-2',
    '!mt-5',
    '!mt-4',
    '!h-auto',
    '!space-y-3',
    '!rotate-180',
    '!border-[#E88209]',
    '!bg-[#E88209]',
    '!right-[3px]',
    'w-full',
    'w-[200px]',
    'relative',
    'rounded-xl',
    'overflow-hidden',
    'flex',
    'justify-center',
    'absolute',
    '-top-3',
    'bg-[#279A2D]',
    'text-white',
    'font-extralight',
    'text-sm',
    'px-4',
    'py-0.5',
    'ring-[5px]',
    'ring-black',
    'rounded-full',
    'bg-[#EB8307]',
    'relative',
    'w-full',
    'flex',
    'justify-between',
    'text-white',
    'px-2.5',
    'bottom-12',
    'h-10',
    'flex',
    'justify-center',
    'items-center',
    'gap-2',
    'p-3',
    'bg-black',
    'backdrop-blur-xl',
    'bg-opacity-80',
    'rounded-xl',
    'text-[#ffad49]', 
    'font-light', 
    'h-10', 
    'flex', 
    'items-center', 
    'pt-2',
    'w-6',
    'h-6',
    'flex',
    'justify-center',
    'items-center',
    'gap-1',
    'pt-2',
    'font-normal',
  ],
  theme: {
    extend: {
      container: {
        center: true,
      },
      fontFamily: {
        'sans': ['Vazirmatn, sans-serif'],
      },
    },
  },
  plugins: [],
};